### ISSUE TITLE
Publish jquery-trap-input to bower

### ISSUE THREAD

**Issue by m-j** [julienw/jquery-trap-input#8]
This is really great library. Would be awesome to have it in bower repository.

**Comment by Javilete** [comment]
Hi, is this library in bower repo yet?

**Comment by julienw** [comment]
I let this slip out of my sight, sorry.
I'll look at it during this week-end.

**Comment by Javilete** [comment]
Hello again, any update about that @julienw? 
Thanks in advance

**Comment by m-j** [comment]
Pull request is ready: https://github.com/julienw/jquery-trap-input/pull/9
It has to be reviewed and accepted if OK

**Comment by julienw** [comment]
Thanks a lot, I squashed your PR (along with some simple stylistic fixes) and pushed a v1.2.1 version containing only this change (to make it possible to target a version containing a bower file).

**Comment by Javilete** [comment]
Awesome, thanks!!
